### ISSUE TITLE
Predicition result

### ISSUE THREAD

**Issue by BisoDevil** [vaibhavsatpathy/incremental-reinforcement-learning#1]
Hello,
first I need to thank you for the script it's very helpful but I have an issue when I try to train a model with some images I got a wrong result every time 
here is my folder structure 

```
- images
   - cat
      -image1.png
      - image1.png  
   - dog  
      - image1.png
      - image2.png

```

sorry I'm new in machine learning and wanna use this script to create a classification model with user data input
so I read about incremental learning after a very long time of searching I got this article which led me to this repo

**Comment by vaibhavsatpathy** [comment]
did you happen to check what were the label encodings which were stored while the model trained. or where you able to take a look at the metrics of the model by any chance?
If you are exploring AI I would recommend check out this link, it may help you a lot with building solutions for clients and different users - [https://chroniclesofai.com/](url)

**Comment by BisoDevil** [comment]
I noticed this script use just one image for training model may be this is the issue for wrong result when predict image

**Comment by vaibhavsatpathy** [comment]
If you notice the base model uses the same batch concept to train, where the batch is size mentioned as 16. I would say if you could check your labels which are being passed that should help you analyse the problem.
If not then check the base model which once trained is it giving the expected results.

**Comment by gcspkmdr** [comment]
Commendable work! Can you please explain the penalty in more detail for both scenarios new labels and wrong predictions?
Also if you can refer me to research or similar from where you have drawn your work.
Appreciate your hard work
Thanks

P.S. I was able to execute your code with my custom architecture and data

**Comment by vaibhavsatpathy** [comment]
> Commendable work! Can you please explain the penalty in more detail for both scenarios new labels and wrong predictions?
> Also if you can refer me to research or similar from where you have drawn your work.
> Appreciate your hard work
> Thanks
> 
> P.S. I was able to execute your code with my custom architecture and data

I am glad that it could be of help. 
As for the penalty, it's basically built on the concept of reinforcement training.
So every time the system makes a wrong prediction, we send back that information to the model for learning features out of it.
Now thinking about it intuitively, there is a likeliness that because of your real time data which may introduce some bias in the model.
So to avoid that we also have placed in a GAN[optional] that would add synthetic data to the penalty batch so that the model doesn't get introduced to any sort of bias.

Most of it is novel work so no literature work around the same.
Things are explained a bit in detail in this blog - [https://medium.com/analytics-vidhya/incremental-and-reinforced-learning-for-image-classification-d02b7a6b7d07](url)
As for rest of my work that I do and content to read around the same can be found here - https://chroniclesofai.com/

**Comment by vaibhavsatpathy** [comment]
If the issue has been resolved, let me know and I would close the issue.

**Comment by gcspkmdr** [comment]
I want to understand the difference between the penalty between the 2 punishments [wrong predictions & new label]

**Comment by vaibhavsatpathy** [comment]
As you can see they cater to 2 different kinds of problems.
1. New Label - One can also say that this might be re-training with the previous learnings added to it. So it would potentially be either transfer learning but preserving the previous label or re-training with the old + new data
2. Wrong predictions - In such case you need not change the architecture of the Neural Network but just pass updated data for existing labels and update the weights.

In case one, you would need to change the architecture as you would be adding new labels to the architecture while preserving the original ones.

So the approach to solve both the situations become different. As you can see that it takes intuitive understanding of how a human brain would function and mimics it into a piece of code, algorithmically.

**Comment by vaibhavsatpathy** [comment]
Again as this is not an issue I would be closing this.
If you have any queries or want to have detailed discussion around the same, please feel free to drop a note on - vaibhavsatpathy@gmail.com
